# Generated by Django 5.2.1 on 2025-05-31 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture (optional)', null=True, upload_to='profile_pictures/')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for notifications', max_length=15)),
                ('preferred_theme', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto (System)')], default='light', help_text='Preferred UI theme', max_length=10)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications for expiring items')),
                ('expiry_reminder_days', models.IntegerField(default=3, help_text='Days before expiry to send reminders')),
                ('low_stock_notifications', models.BooleanField(default=True, help_text='Receive notifications for low stock items')),
                ('default_grocery_category', models.CharField(default='Other', help_text='Default category for new items', max_length=50)),
                ('items_per_page', models.IntegerField(default=12, help_text='Number of items to display per page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('item_added', 'Item Added'), ('item_updated', 'Item Updated'), ('item_deleted', 'Item Deleted'), ('profile_updated', 'Profile Updated'), ('list_shared', 'List Shared'), ('export_data', 'Data Exported')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='accounts_us_user_id_5cc93e_idx'), models.Index(fields=['action'], name='accounts_us_action_ec31c8_idx')],
            },
        ),
    ]
